version: '3.6'
services:
  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vertx-quartz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./sql/quartz-init.sql:/docker-entrypoint-initdb.d/quartz-init.sql